# Generated by Django 3.2.15 on 2022-10-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('engine', models.TextField()),
                ('description', models.TextField()),
                ('specs', models.TextField()),
            ],
        ),
    ]
